# Generated by Django 5.1.3 on 2024-11-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ancestry', models.CharField(max_length=50)),
                ('background', models.CharField(max_length=50)),
                ('ch_class', models.CharField(max_length=50)),
                ('str', models.IntegerField()),
                ('dex', models.IntegerField()),
                ('con', models.IntegerField()),
                ('int', models.IntegerField()),
                ('wis', models.IntegerField()),
                ('cha', models.IntegerField()),
                ('acrobatics', models.BooleanField()),
                ('animal_handling', models.BooleanField()),
                ('arcana', models.BooleanField()),
                ('athletics', models.BooleanField()),
                ('deception', models.BooleanField()),
                ('history', models.BooleanField()),
                ('insight', models.BooleanField()),
                ('intimidation', models.BooleanField()),
                ('investigation', models.BooleanField()),
                ('medicine', models.BooleanField()),
                ('nature', models.BooleanField()),
                ('perception', models.BooleanField()),
                ('performance', models.BooleanField()),
                ('persuasion', models.BooleanField()),
                ('religion', models.BooleanField()),
                ('sleight_of_hand', models.BooleanField()),
                ('stealth', models.BooleanField()),
                ('survival', models.BooleanField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
