# Generated by Django 5.1.3 on 2024-11-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ch_image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
